In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# IMPORT

In [5]:
import numpy as np

In [6]:
print(np.__version__)

2.1.3


# Create Array

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Type:", type(arr))


Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


# Multi-Dimensional Array

In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:", arr2)


2D Array:
 [[1 2 3]
 [4 5 6]]


# Useful Array Functions

In [5]:
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())


Sum: 15
Mean: 3.0
Max: 5
Min: 1


# Range and Zeros

In [6]:
print("Range Array:", np.arange(1, 10))   
print("Zeros Array:", np.zeros((2, 3)))  


Range Array: [1 2 3 4 5 6 7 8 9]
Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]]


# Random Arrays 

In [7]:
print("Random Array:", np.random.randint(1, 10, size=(2, 3)))


Random Array: [[1 1 9]
 [8 4 7]]


# np.ones

In [9]:
print("np.ones:", np.ones((2, 3)))

np.ones: [[1. 1. 1.]
 [1. 1. 1.]]


# np.zeros

In [10]:
print("np.zeros:", np.zeros((5)))

np.zeros: [0. 0. 0. 0. 0.]


In [ ]:
arr3 = np.arange(1, 7)   
print("Original:", arr3)
print("Reshaped 2x3:", arr3.reshape(2, 3))


# Array operations

In [7]:
nums = np.array([10, 20, 30])

print("Add 5:", nums + 5)
print("Multiply 2:", nums * 2)
print("Array + Array:", nums + np.array([1, 2, 3]))
print("Dot Product:", nums.dot(np.array([1, 0, 1])))


Add 5: [15 25 35]
Multiply 2: [20 40 60]
Array + Array: [11 22 33]
Dot Product: 40


# Indexing and slicing

In [8]:
print("First element:", nums[0])
print("Last element:", nums[-1])
print("Slice 1:3:", nums[1:3])
print("Every 2nd element:", nums[::2])

First element: 10
Last element: 30
Slice 1:3: [20 30]
Every 2nd element: [10 30]


# sorting and unique

In [10]:
arr4 = np.array([3, 1, 2, 3, 4, 2, 1])
print("Sorted:", np.sort(arr4))
print("Unique:", np.unique(arr4))

Sorted: [1 1 2 2 3 3 4]
Unique: [1 2 3 4]


# Boolean

In [11]:
marks = np.array([45, 67, 89, 30, 55])
print("Marks > 50:", marks[marks > 50])
print("Indices where > 50:", np.where(marks > 50))

Marks > 50: [67 89 55]
Indices where > 50: (array([1, 2, 4]),)


# 3 Dimensional Array

In [15]:
arr3 = np.array([[[12,46,23] , [34,75,39] , [34,57,15]]])
print("3D array:", arr3)

3D array: [[[12 46 23]
  [34 75 39]
  [34 57 15]]]


# Matrix

In [16]:
import numpy as np

mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(mat)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Add and subtract

In [17]:
mat2 = np.array([[9,8,7],
                 [6,5,4],
                 [3,2,1]])
print(mat + mat2)   
print(mat - mat2)   


[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


# Reshape(array change in matrix)

In [18]:
arr = np.arange(1,7)   
print(arr.reshape(2,3))


[[1 2 3]
 [4 5 6]]


# Identity Matrix

In [19]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Convert 2D to 1D

In [2]:
import numpy as np

# 2D matrix
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original 2D Matrix:")
print(mat)

# Convert to 1D
one_d = mat.flatten()
print("\nConverted 1D Array:")
print(one_d)


Original 2D Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Converted 1D Array:
[1 2 3 4 5 6 7 8 9]


In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\Gateway\\Desktop\\seattle-weather.csv")

In [4]:
df

date  precipitation  temp_max  temp_min  wind  weather
0       1/1/2012            0.0      12.8       5.0   4.7  drizzle
1       1/2/2012           10.9      10.6       2.8   4.5     rain
2       1/3/2012            0.8      11.7       7.2   2.3     rain
3       1/4/2012           20.3      12.2       5.6   4.7     rain
4       1/5/2012            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  12/27/2015            8.6       4.4       1.7   2.9     rain
1457  12/28/2015            1.5       5.0       1.7   1.3     rain
1458  12/29/2015            0.0       7.2       0.6   2.6      fog
1459  12/30/2015            0.0       5.6      -1.0   3.4      sun
1460  12/31/2015            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]